rGallery/rgallery/config/routes.rb
Rails.application.routes.draw do
  

  # get 'images/new', changing this so that new actions takes to path called upload.
  get "upload" => "images#new", :as => "upload"

  
  get 'images/create'
  get 'images/destroy'
 
  root 'images#index'
  
  get 'categories/new'
  get 'categories/create'
  get 'categories/destroy'
  get 'categories/index'
  get 'categories/new'
  get 'categories/create'
  get 'categories/edit'
  get 'categories/update'
  get 'categories/destroy'
  get 'categories/show'
 
  resources :images, :categories

end

rGallery/rgallery/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rGallery/rgallery/app/models/category.rb
class Category < ApplicationRecord
	has_many :images
end

rGallery/rgallery/app/models/image.rb
class Image < ApplicationRecord
	belongs_to :category

	mount_uploader :image, ImageUploader

	before_save :update_image_attributes

	private
	def update_image_attributes
		if image.present? && image_changed?
			self.image_content_type = image.file.content_type
			self.image_file_size = image.file.size
		end
	end
end

rGallery/rgallery/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :getCategoryNav

	private
	def getCategoryNav
		@categoryNav = Category.all		
	end


end

rGallery/rgallery/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category created ..."
      redirect_to root_path
    else
      render 'new'
    end
  end

# edit and show methods have same working as both are used in the same view
  def edit
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = "Category updated ..."
      redirect_to category_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    flash[:notice] = "Category Removed"
    redirect_to root_path
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images
  end


  private
  def category_params
    params.require(:category).permit(:name)       
  end

end

rGallery/rgallery/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  def new
  	@image = Image.new
  end

  def create
  	@image = Image.new(image_params)

    if @image.save
      flash[:notice] = "Image added ..."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    flash[:notice] = "Image Removed"
    redirect_to images_path
  end

  def index
    @images = Image.all
    @categories = Category.all
  end

  private
  def image_params
    params.require(:image).permit(:image_title,:image, :category_id, :image_description, :image_file_size, :image_content_type, :remote_image_url)       
  end

end

rGallery/rgallery/app/helpers/application_helper.rb
module ApplicationHelper
end

rGallery/rgallery/app/helpers/categories_helper.rb
module CategoriesHelper
end

rGallery/rgallery/app/helpers/images_helper.rb
module ImagesHelper
end

rGallery/rgallery/app/views/categories/edit.html.erb
<div class="container" id="form-box">
	<h1 style="font-family: 'Finger Paint', cursive; text-align: center;">Edit Category</h1>
	<h4 style="font-family: 'Finger Paint', cursive;margin-top: 0;text-align: center;"> "lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"</h4><br>

	<%= form_for @category do |f| %>
		<!-- check for errors -->
		<% if @category.errors.any? %>
			<% @category.errors.full_messages_each do |msg| %>
			<!-- show errors -->
			<div class="alert alert-message"><%= msg %></div>
			<% end %>
		<% end %>

		<div class="form-group">
			<%= f.text_field :name, placeholder: "Name", class:"form-control" %>
		</div>
		<%= f.submit "Submit", class:"btn btn-dark" %>
		<%= link_to "Cancel", root_path, class:"btn btn-light" %>
	<% end %>
</div>

<div class="container" style="margin-top: 5%;">Images in <%= @category.name %><hr>
<div id="edit_images">
	<% if @images.exists? %>
		<% @images.each_slice(6) do |image| %>
		<div class="row">
			<% image.each do |image| %>
				<div class="col-md-2">
					<%= image_tag image.image_url(:thumb) %>
					<center><%= link_to "Remove", image_path(image), method: :delete, class:"delete-link" %></center>
				</div>
			<% end %>
		</div>
		<% end %>
	<% end %>
</div>
</div>

<style type="text/css">
	#form-box {
		background: rgba(255,255,255,.5);
    	padding: 15%;
    	padding-top: 8%;
    	padding-bottom: 8%;
    	border: 2px solid #666;
	}
	.delete-link, .delete-link:hover {
		text-decoration: none;
		font-size: 10px;
		color: crimson;
	}
</style>

rGallery/rgallery/app/views/categories/new.html.erb
<div class="container" id="form-box">
	<h1 style="font-family: 'Finger Paint', cursive; text-align: center;">New Category</h1>
	<h4 style="font-family: 'Finger Paint', cursive;margin-top: 0;text-align: center;"> "lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"</h4><br>

	<%= form_for @category do |f| %>
		<!-- check for errors -->
		<% if @category.errors.any? %>
			<% @category.errors.full_messages_each do |msg| %>
			<!-- show errors -->
			<div class="alert alert-message"><%= msg %></div>
			<% end %>
		<% end %>

		<div class="form-group">
			<%= f.text_field :name, placeholder: "Name", class:"form-control" %>
		</div>
		<%= f.submit "Submit", class:"btn btn-dark" %>
		<%= link_to "Cancel", root_path, class:"btn btn-light" %>
	<% end %>
</div>

<style type="text/css">
	#form-box {
		background: rgba(255,255,255,.5);
    	padding: 15%;
    	padding-top: 8%;
    	padding-bottom: 8%;
    	border: 2px solid #666;
	}
</style>

rGallery/rgallery/app/views/categories/show.html.erb
<small"><%= link_to "Edit", edit_category_path, class:"edit-style" %></small>
<div id="gallery" uk-lightbox="animation: scale">
  <h3 id="for-mobile"><%= @category.name %></h3>

  <% if @images.exists? %>
    <% @images.each_slice(4) do |image| %>
      <div class="row">
        <% image.each do |i| %>
          <div class="col-md-3">
            <div class="photo photo-type-line">
              <!-- image_url field was not made by us, carrierwave gives it to us! -->
              <a href="<%= i.image_url %>" class="photo-hover" data-caption="<%= i.image_title %>">
                <div class="photo-info">
                  <div class="headline"><%= i.image_title%></div>
                  <div class="line"></div>
                  <div class="desc"><%= i.image_description %></div>
                </div>
                <div class="mask"></div>
              </a>
              <div class="photo-img"><%= image_tag i.image_url(:thumb) %> </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <% else %>
      <p>We ain't have any image yet...</p>
  <% end %> 
</div>


<style type="text/css">
  .edit-style, .edit-style:hover {
    position: absolute;
    color: darkgrey;
    text-decoration: none;
    margin-left: 65%;
    margin-top: 1%;
  }
  .edit-style:hover {
    color: black;
  }

  @media only screen and (orientation: portrait) {
    #for-mobile {
      margin-right: 10%;
    }
}
</style>

rGallery/rgallery/app/views/images/index.html.erb
<div id="gallery" uk-lightbox="animation: scale">
  <h3 id="for-mobile"> All Images </h3>

  <% if @images.exists? %>
    <% @images.each_slice(4) do |image| %>
      <div class="row">
        <% image.each do |i| %>
          <div class="col-md-3">
            <div class="photo photo-type-line">
              <!-- image_url field was not made by us, carrierwave gives it to us! -->
              <a href="<%= i.image_url %>" class="photo-hover" data-caption="<%= i.image_title %>">
                <div class="photo-info">
                  <div class="headline"><%= i.image_title%></div>
                  <div class="line"></div>
                  <div class="desc"><%= i.image_description %></div>
                </div>
                <div class="mask"></div>
              </a>
              <div class="photo-img"><%= image_tag i.image_url(:thumb) %> </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <% else %>
      <p>We ain't have any image yet...</p>
  <% end %> 
</div>

<style type="text/css">
   @media only screen and (orientation: portrait) {
    #for-mobile {
      margin-right: 15%;
    }
}
</style>

rGallery/rgallery/app/views/images/new.html.erb
<div class="container" id="form-box">
	<h1 style="font-family: 'Finger Paint', cursive; text-align: center;">Add an image</h1>
	<h4 style="font-family: 'Finger Paint', cursive;margin-top: 0;text-align: center;"> "lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut"</h4><br>


<!-- :html => {:multipart => true}  enables us to have a file_field for image -->
	<%= form_for @image, :html => {:multipart => true} do |f| %>
		<!-- check for errors -->
		<% if @image.errors.any? %>
			<% @image.errors.full_messages_each do |msg| %>
			<!-- show errors -->
			<div class="alert alert-message"><%= msg %></div>
			<% end %>
		<% end %>

		<div class="form-group">
			<%= f.label :image %><br>
			<%= f.file_field :image%>
		</div>
		<div class="form-group">
			<%= f.label :image_title %>
			<%= f.text_field :image_title, placeholder: "Enter a suitable title for your image", class:"form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :category %>
			<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select from the list below or create a new one'}, class:"form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :image_description %>
			<%= f.text_field :image_description, placeholder: "What does your image say? Make it interesting!", class:"form-control" %>
		</div>
		<div class="form-group">
			<%#= f.label :remote_image_url, 'or image url' %>
			<%#= f.text_field :remote_image_url, placeholder: "Don't want to upload? Put an image link from the internet here!", class:"form-control" %>
		</div>
		<hr>

		<%= f.submit "Submit", class:"btn btn-dark" %>
		<%= link_to "Cancel", root_path, class:"btn btn-light" %>
	<% end %>
</div>


<style type="text/css">
	#form-box {
		background: rgba(255,255,255,.5);
    	padding: 15%;
    	padding-top: 8%;
    	padding-bottom: 8%;
    	border: 2px solid #666;
	}
</style>

rGallery/rgallery/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <title>Imagene | Aikansh</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Finger+Paint" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
    
    
      <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.21/css/uikit.min.css" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <%= link_to "IMAGENE!", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">

<!--this loops through every category in the database and adds it to our navbar. To access  @categoryNav in every view, we defined it in application controller!-->
          <% @categoryNav.each do |category| %>
            <li class="nav-item">
              <%= link_to category.name, category_path(category.id), class: "nav-link"%>
            </li>
          <% end %>          
        </ul>

        <ul class="navbar-nav pull-right">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Manage</a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown01">
              <%= link_to "Upload Photo", upload_path, class: "dropdown-item"%>
              <%= link_to "New Category", new_category_path, class: "dropdown-item"%>
              <%#= link_to "Delete Photo", image_path(), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item"%>
            </div>
          </li>
        </ul>
      </div>
    </nav>
<!-- ------------------------------------------------------- -->
    
    <div class="container" id="for-mobile">
    <!-- alerts and messages -->
    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice]%></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert]%></div>
    <% end %>

      <%= yield %>
    
    </div>

<!-- ------------------------------------------------------- -->

    <footer>
      Copyright &copy; 2018, Aikansh Garg
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- UIkit JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.21/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.21/js/uikit-icons.min.js"></script>


  </body>
</html>


<!-- 
cont. style="padding-left: 17%;"
edit -->

<style type="text/css">
  @media only screen and (orientation: portrait) {
    #for-mobile {
      padding-left: 15%;
    }
}
</style>